# Generated by Django 4.2.29 on 2026-05-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_community_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
